name: Diamond Emergency Pause

on:
  push:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  diamond-emergency-pause:
    runs-on: ubuntu-latest

    steps:
      - name: Check user permissions
        id: check_user
        run: |
          ALLOWED_USERS=("0xDEnYO" "maxklenk" "ezynda3")
          if [[ ! " ${ALLOWED_USERS[@]} " =~ " ${{ github.actor }} " ]]; then
            echo "User ${{ github.actor }} is not allowed to run this workflow."
            exit 1
          fi
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: EmergencyPauseGithubAction # Ensure you are checking out the correct branch

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # - name: Install Solidity Libs
      #   run: forge install

      - name: Run diamondEMERGENCYPause script
        run: |
          ./script/tasks/diamondEMERGENCYPauseGitHub.sh
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          ETH_NODE_URI_MAINNET: ${{ secrets.ETH_NODE_URI_MAINNET }}
          ETH_NODE_URI_POLYGON: ${{ secrets.ETH_NODE_URI_POLYGON }}
          ETH_NODE_URI_BSC: ${{ secrets.ETH_NODE_URI_BSC }}
          PRIVATE_KEY_PAUSER_WALLET: ${{ secrets.TEST_PRIV_KEY_SECRET }}

      - name: Send Discord message
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'ATTENTION - the emergency diamond pause action was just executed by ${{ github.actor }}'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
