name: Diamond Emergency Pause

on:
  push:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  diamond-emergency-pause:
    runs-on: ubuntu-latest

    steps:
      - name: Check user permissions
        id: check_user
        run: |
          ALLOWED_USERS=("0xDEnYO" "maxklenk" "ezynda3")
          if [[ ! " ${ALLOWED_USERS[@]} " =~ " ${{ github.actor }} " ]]; then
            echo "User ${{ github.actor }} is not allowed to run this workflow."
            exit 1
          fi
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main # Ensure you are checking out the correct branch

      - name: Debug - List files
        run: ls -R

      - name: Debug - Print current directory
        run: pwd

      - name: Debug - Check file existence
        run: |
          if [ -f script/tasks/diamondEmergencyPause2.sh ]; then
            echo "File exists"
          else
            echo "File does not exist"
          fi

      - name: Run diamondEMERGENCYPause script
        run: |
          chmod +x script/tasks/diamondEmergencyPause2.sh
          ./script/tasks/diamondEmergencyPause2.sh
        env:
          PRIVATE_KEY_PAUSER_WALLET: ${{ secrets.TEST_SECRET }}
