name: Find team members

on:
  push:
  workflow_dispatch:

jobs:
  get-team:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch team data
        # We add the id to access to this step outputs
        id: teams
        uses: paritytech/list-team-members@main
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          team: diamondpausers
          # optional, in case that it searches on a different organization
          organization: lifinance
        # example showing how to use the content
      - name: Show data
        run: |
          echo "The users are $USERNAMES"
          echo "Data: $DATA"
        env:
          USERNAMES: ${{ steps.teams.outputs.usernames }}"
          # a json object
          DATA: ${{ steps.teams.outputs.team-data }}"
